spring:
  application:
    name: Order_service_2

  kafka:
    bootstrap-servers: kafka-1:29092,kafka-2:29192,kafka-3:29392
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        acks: all
        retries: 3
        enable.idempotence: true
        reconnect.backoff.ms: 5000
        reconnect.backoff.max.ms: 30000
        spring.kafka.consumer.properties.metadata.max.age.ms: 30000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order_service_2_group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.type.mapping: >
          org.example.transactional_service.OrderSavedEvent:org.example.order_service_2.OrderSavedEvent,
          org.example.transactional_service_2.OrderSavedEvent:org.example.order_service_2.OrderSavedEvent
        spring.json.trusted.packages: >
          org.example.logger_service,
          org.example.order_service,
          org.example.order_service_2,
          org.example.transactional_service,
          org.example.transactional_service_2
        spring.json.use.type.headers: true
        isolation.level: read_committed
        reconnect.backoff.ms: 5000
        reconnect.backoff.max.ms: 30000
        spring.kafka.consumer.properties.metadata.max.age.ms: 30000
    listener:
      ack-mode: manual_immediate

server:
  port: 8082